language: node_js
sudo: false
node_js:
  - "6"
  - "7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
cache:
    directories:
    — node_modules
install:
  - npm install
script:
  - npm test
