language: node_js
sudo: false
node_js:
  - "6"
  - "7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
install:
  - npm install
  - npm install -g codecov
script:
  - npm test --single-run --code-coverage --reporters coverage-istanbul
