language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
before_install:
  - npm i npm@^4 -g
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - sleep 3
script:
  - ng test
